### ISSUE TITLE
display verzia kodu a subor asociovany s predmetom su rozne

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/ais-infolisty#2]
Display verzia kodu predmetu by mala byt: 3-MAM-014/00
Subor asociovany s predmeto by mal byt: 3-MAM-014_00.html

**Comment by TomiBelan** [comment]
Pridal som RewriteRule, tak uz funguje aj https://sluzby.fmph.uniba.sk/infolist/sk/1-AIN-105/15 .

**Comment by TomiBelan** [comment]
Aha, asi stale treba trochu upravit skript, lebo v tele stranky je zly kod:

> **Kód:** 1-AIN-105_15

**Comment by tvinar** [comment]
Ano, to je presne to, co treba dorobit ;)
Idea je, ze vsade ma byt zobrazovany kod s / ale linka ma byt s _
Takisto su tam drobnosti tykajuce sa kodov - nie vsetky sa nahradzuju
linkami
(napr. tie v obsahovych prerekvizitach)



On Thu, Aug 13, 2015 at 11:15 PM, Tomi Belan <notifications@github.com>
wrote:

> Aha, asi stale treba trochu upravit skript, lebo v tele stranky je zly kod:
>
> *Kód:* 1-AIN-105_15
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fmfi-svt/ais-infolisty/issues/2#issuecomment-130846732>
> .
>



-- 
--------------------------------------------------------------------------
Tomas Vinar, Assistant Professor and Independent Researcher
Associate Dean for Information Technologies
Department of Applied Informatics
Faculty of Mathematics, Physics, and Informatics
Comenius University, Bratislava
E-mail: tomas.vinar@fmph.uniba.sk
Office: M163
Work Phone: +421-2-60295207
