### ISSUE TITLE
Lomka v skratke studijneho programu

### ISSUE THREAD

**Issue by crnkjck** [fmfi-svt/ais-infolisty#5]
Konverzne programy maju v AIS skratky `…/k`. Konvertuju sa tieto lomky v stabilnych URL `https://sluzby.fmph.uniba.sk/infolist/sk/sp_skratka.html` na `_` alebo ostavaju ako `/`?

**Comment by TomiBelan** [comment]
V mene suboru je `-`. Ale spravil som RewriteRule, aby fungovalo aj `/`. Napriklad: https://sluzby.fmph.uniba.sk/infolist/sk/sp_dAAF_AU/x
